[package]
name = "gfx_game"
version = "0.1.0"
authors = ["sirkibsirkib <christopher.esterhuyse@gmail.com>"]
edition = "2018"

[dependencies]
gfx_pp = { path = "C:/Git/gfx_pp" }
rand = "0.6"
specs = "0.14.3"
hashbrown = "0.1.8"
specs-derive = "0.4.0"
enum-map = "0.5.0"